# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - githbaction45

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_f57531d880674ca0bb79eb638db6744b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_99df5a24e89f433182129bfa27182b30 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_f57531d880674ca0bb79eb638db6744b }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'githbaction45'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_12e461fb7eea43248fff21085f4ee8ed }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_f57531d880674ca0bb79eb638db6744b }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}'